name: flutter_biolerplate
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.0
  dio_cache_interceptor_hive_store: ^3.2.0
  connectivity_plus: ^2.3.5
  url_launcher: ^6.1.4
  shared_preferences: ^2.0.15
  material_color_utilities: ^0.1.4
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  equatable: ^2.0.3
  formz: ^0.4.1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
